export const PRESENTES = [
  { nome: 'Sofá 3 lugares retrátil', marcas: '', cor: 'Cinza escuro, Marron, Bege escuro' },
  { nome: 'Microondas 30+ litros', marcas: '', cor: 'Preto, Branco ou Prata' },
  { nome: 'Máquina de lavar 10kg+', marcas: 'Brastemp, Consul ou Electrolux', cor: '' },
  // { nome: 'Secadora de roupas 8kg+', marcas: '', cor: '' },
  { nome: 'Forno elétrico 30+ litros', marcas: '', cor: '' },
  { nome: 'Roupão de banho M feminino', marcas: '', cor: '' },
  { nome: 'Roupão de banho G masculino', marcas: '', cor: '' },
  { nome: 'Jogo de panelas inox', marcas: '', cor: '' },
  { nome: 'Jogo de talheres inox', marcas: '', cor: '' },
  { nome: 'Jogo de 6 cadeiras para mesa de madeira angelim', marcas: '', cor: '' },
  { nome: 'Chaleira elétrica', marcas: '', cores: '' },
  { nome: 'Colchão de solteiro D33(2)', marcas: '', cores: '' },
  { nome: 'Jogo de lençol casal (3)', marcas: '', cores: '' },
  { nome: 'Jogo de lençol solteiro (3)', marcas: '', cores: '' },
  { nome: 'Toalhas de banho (6)', marcas: '', cores: '' },
  { nome: 'Jogo de taças de vinho', marcas: '', cores: '' },
  { nome: 'Jogo de tapetes banheiro (3)', marcas: '', cores: '' },
  { nome: 'Capacho de bem vindo', marcas: '', cores: '' },
];
